---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Make sure user is added to microk8s group
      ansible.builtin.user:
        name: ckaserer
        groups: microk8s
        append: true
      register: microk8s_verify
      failed_when: microk8s_verify.changed
      tags:
        - microk8s
        - microk8s.user
        - microk8s.user.group

    - name: Make sure dependencies are installed
      ansible.builtin.apt:
        name:
          - snapd
          - fuse
          - udev
        state: present
      check_mode: true
      register: microk8s_verify
      failed_when: microk8s_verify.changed
      tags:
        - microk8s
        - microk8s.dependencies
        - microk8s.dependencies.apt

    - name: Start and Enable Services
      ansible.builtin.service:
        name: "{{ microk8s_service }}"
        state: started
        enabled: true
      with_items:
        - snapd
        - udev
      loop_control:
        loop_var: microk8s_service
        label: "{{ microk8s_service }}"
      check_mode: true
      register: microk8s_verify
      failed_when: microk8s_verify.changed
      tags:
        - microk8s
        - microk8s.dependencies
        - microk8s.dependencies.services

    - name: Install microk8s
      community.general.snap:
        name: microk8s
        classic: true
      check_mode: true
      register: microk8s_verify
      failed_when: microk8s_verify.changed
      tags:
        - microk8s
        - microk8s.install

    - name: Create kubectl alias
      ansible.builtin.shell:
        cmd: command -v /snap/bin/kubectl >/dev/null 2>&1
      changed_when: false
      tags:
        - microk8s
        - microk8s.alias
        - microk8s.alias.kubectl

    - name: Create folder for microk8s certificates
      ansible.builtin.file:
        path: /usr/share/ca-certificates/extra
        state: directory
        mode: 0755
      check_mode: true
      register: microk8s_verify
      failed_when: microk8s_verify.changed
      tags:
        - microk8s
        - microk8s.certs
        - microk8s.certs.dir

    - name: Copy certificates
      ansible.builtin.copy:
        src: "{{ microk8s_ca }}"
        dest: /usr/share/ca-certificates/extra
        remote_src: true
        force: true
        mode: 0644
      loop_control:
        loop_var: microk8s_ca
        label: "{{ microk8s_ca }}"
      with_fileglob:
        - /var/snap/microk8s/current/certs/*ca*.crt
      check_mode: true
      register: microk8s_verify
      failed_when: microk8s_verify.changed
      tags:
        - microk8s
        - microk8s.certs
        - microk8s.certs.copy

    - name: Trust certificates generated by microk8s
      ansible.builtin.command:
        cmd: "update-ca-certificates"
      register: microk8s_cmd_result
      changed_when: "'0 added, 0 removed' not in microk8s_cmd_result.stdout"
      failed_when: "'0 added, 0 removed' not in microk8s_cmd_result.stdout"
      tags:
        - microk8s
        - microk8s.certs
        - microk8s.certs.trust
...
