---
name: Main

'on':
  push:
    branches:
      - main
    tags-ignore:
      - '**'

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3

  super-linter:
    name: Github Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base with github super-linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          FILTER_REGEX_EXCLUDE: '.*.md'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JSCPD: false
          VALIDATE_GITHUB_ACTIONS: false

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2004
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: gepaplexx.microk8s

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        working-directory: gepaplexx.microk8s
        run: pip3 install -r requirements.txt

      - name: Run Molecule tests
        run: molecule test
        working-directory: gepaplexx.microk8s
        env:
          PY_COLORS: 1
          ANSIBLE_FORCE_COLOR: 1
          MOLECULE_DISTRO: ${{ matrix.distro }}

  release:
    name: Release
    if: ${{ github.event_name != 'schedule' }}
    runs-on: ubuntu-latest
    needs:
      - pre-commit
      - super-linter
      - molecule
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create a new tag
        uses: phish108/autotag-action@1.1.37
        id: autotag
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a new release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.autotag.outputs.new-tag }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install ansible-base
        run: pip3 install ansible-base

      - name: Trigger a new import on Galaxy
        run: >-
          ansible-galaxy role import
          --token "${{ secrets.GALAXY_API_KEY }}"
          --branch main
          "$(echo ${{ github.repository }} | cut -d/ -f1)"
          "$(echo ${{ github.repository }} | cut -d/ -f2)"


  notify:
    name: Slack Notifications
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs:
      - release
    steps:
      - name: Notify Slack channel on failure
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://github.com/ckaserer/logos/raw/master/ansible.png
          SLACK_USERNAME: ${{ github.repository }}
          SLACK_COLOR: '#ff0033'
          SLACK_FOOTER: ''
...
